### ISSUE TITLE
type: object does not enforce additionalProperties: false

### ISSUE THREAD

**Issue by majsan** [spraakbanken/karp-backend#291]
If `additionalProperties: false` is set, no unconfigured should be fields accepted. However, that only works on the top level, so an entry:

```
{ "apa": {"bepa": 1, "cepa": 2}}
```

is valid with config
```
fields:
    apa:
        type: object
        fields:
            bepa:
                type: "string"
additionalProperties: false
```

But Karp should not allow this.
